### GET / homepage
GET http://localhost:5003

###Register
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "Katie",
    "password": "password123"
}

### Login
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "Katie",
    "password": "password123"
}